<script>
function back_to_listing(){
	window.location = '<?=$this->baseUrl()?>/admin';
}


</script>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
                <?php if(isset($this->message)){ echo $this->message;}?>
                <div id="addEvent">
                <form name="edituser" action="" method="post">
                			  <?
							  
							  if($_POST)
							  {
							   $this->form->populate(
                                  		array
                                            (
                                                'first_name'=>$_POST['first_name'],
                                                'last_name'=>$_POST['last_name'],
						'user_intial'=>$_POST['user_intial'],
                                                'user_email'=>$_POST['user_email'],
						//'user_type'=>$_POST['user_type'],
                                               'user_type'=>'1',
						//'user_status'=>'Active',
						'cust_password'=>'', 
                                            )
                                  );
								 
							  
							  }else
							  {
							  
                               	  $this->form->populate(
                                  		array
                                            (
                                                'first_name'=>$this->rst['fname'],
                                                'last_name'=>$this->rst['lname'],
						 'user_intial'=>$this->rst['user_initial'],
                                                'user_email'=>$this->rst['email'],
												//'user_type'=>$this->rst['role'],
												//'user_status'=>$this->rst['status'],
										        
                                            )
                                  );
								 
								}
                               
                               ?>
               				    <?=$this->form->first_name?>
                                <label><?=$this->translate('First Name')?>*</label>
                             	 <?=$this->form->last_name?>
                                <label><?=$this->translate('Last Name')?>*</label>   
                      			  <? if(isset($this->userinitialError)&& $this->userinitialError!=''){echo '<div class= "errors"><ul><li>'.$this->userinitialError.'</li></ul></div>';}?>  
								 <?=$this->form->user_intial?>
                                <label><?=$this->translate('User Name')?>*</label>   
                      			<? if(isset($this->editError)&& $this->editError!=''){ 
								 $this->form->populate(
                                  		array
                                            (
											'user_email'=>$_POST['user_email'],
											)
                                  );
								 echo '<div class= "errors"><ul><li>'.$this->editError.'</li></ul></div>';}?>   
								 <?=$this->form->user_email?> 
                                <label><?=$this->translate('Email')?>*</label>
                                <?=$this->form->cust_password?>
                                <label><?=$this->translate('Password')?></label>
                                <?=$this->form->cust_confirm_password?>
                                <label><?=$this->translate('Confirm Password')?></label>          
                              <!--  <?//=$this->form->user_type?>
                                <label><?//=$this->translate('User Type')?>*</label>
                                
                    <table>
                      	<tr class="autoWidth">
                           	<td class="list-radio">
								<?//=$this->form->user_status?>
                                <div class="clr" style="height:0px;"></div>
                                <label for="status"><?//=$this->translate('Status')?>*</label>
                            </td>
                        </tr>
                    </table> -->
                   
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->translate('Save')?>"/>
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
<?
if(isset($this->addError)&& $this->addError!='')
{
?>
<script>
$('#event_cost_dis').show();
</script>
<?
}
/*elseif($_POST)
{
	if($_POST['user_type']==32)
	{
		if(isset($_POST['event_cost']))
		{
?>
<script>
$('#event_cost_dis').show();
$('#event_cost').value=<?=$_POST['event_cost']?>;
</script>
<?
		}else{
?>
<script>
$('#event_cost_dis').show();
$('#event_cost').value=<?=$this->rst['user_event_cost']?>;
</script>
<?
			}	
?>
<?
	}
}elseif($this->rst['role']==32)
{
?>
<script>
$('#event_cost_dis').show();
$('#event_cost').value=<?=$this->rst['user_event_cost']?>;
</script>
<?
} */
?>