#!/bin/bash          
echo "Welcome to Git script to make Mueen's life easier :)\n\n"
git add .
git commit --no-verify -am "$1"
git push -u origin master
echo "\n\nMueen's life has been made easy and this script has completed.\n\n"
