<script>
	function sortColumn(col)
	{
		document.getElementById('sort_col').value = col;
		document.link_list_search.submit();
	}

	function setPaging(obj)
	{
		document.getElementById('perPage').value = obj.value;
		document.link_list.submit();
	}
	function getDropDown(val){
		$.ajax({
		  url: '<?=$this->baseUrl()?>/admin/link/dropdown/'+val,
		  dataType: "html",
		  success: function(data) {
			$('#val-input').html(data);
		  }
		});
	}
<?php $session = new Zend_Session_Namespace('Link_Search');?>	
window.onload = getDropDown('<?php echo $session->filter?>');

</script>
<? $session = new Zend_Session_Namespace('Link_Search');

?>
<form name="link_list" id="link_list" action="<?=$this->baseUrl()?>/admin/link/list" method="post">  
   	<input type="hidden" name="perPage" id="perPage" value="<?=$session->perPage?>" />
</form>

<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td bgcolor="#e5e5e5" width="200" height="50">&nbsp;</td>
        <td bgcolor="#ff9900">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Link Management')?></h2></td>
                    <td align="center"><a href="<?=$this->baseUrl()?>/admin/link/add" class="whiteLink"><strong><?=$this->translate('Add link')?></strong></a>&nbsp;&nbsp;<a href="<?=$this->baseUrl()?>/admin/link/listuser" class="whiteLink"><strong><?=$this->translate('User Links')?></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr>
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            
            <div id="eventListing">
            <?=$this->render('common/all-lang-tab.phtml',true)?>
            	<form name="link_list_search" id="link_list_search" method="post" action="<?=$this->baseUrl()?>/admin/link/list">
                    <input type='hidden' name='sort_col' value='' id='sort_col'>
                    <input type="hidden" name="perPage" id="perPage" value="<?=$session->perPage?>" />
                <table class="pagination">
                    <tr>
                        <td align="right">
                           <?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>  
                        </td>
                    </tr>
                </table>
                
                <table class="searchBy">
                    <tr>
                        <td width="52%">&nbsp;</td>
                        <td><?=$this->translate('Search By')?></td>
                        <td><?=$this->searchform->filters?></td>
                        <td><span id="val-input"><?=$this->searchform->filterText?></span></td>
                        <td class="btn"><input name="submitAction" type="submit" value="<?=$this->translate('Search')?>" /></td>
                        <td class="btn"><input name="submitAction" type="submit" value="<?=$this->translate('Reset')?>" /></td>
                    </tr>
                </table>
                
                </form>
                
                <table class="listing">
                    <tr class="headings">
                    <th width=""><a href="#" class="link" onClick="sortColumn('link_id')"><?=$this->translate('ID')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_id'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                     <th width=""><a href="#" class="link" onClick="sortColumn('link_category')"><?=$this->translate('Link Cat Id')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_category'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                    
                        <th width=""><a href="#" class="link" onClick="sortColumn('link_name')"><?=$this->translate('Name')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_name'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                        
                         <th width=""><a href="#" class="link" onClick="sortColumn('link_category')"><?=$this->translate('Category')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_category'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                          <th width=""><a href="#" class="link" onClick="sortColumn('link_subcategory')"><?=$this->translate('Subcategory')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_subcategory'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                           <th width=""><a href="#" class="link" onClick="sortColumn('link_trip')"><?=$this->translate('Travle Phase')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_trip'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                            <th width=""><a href="#" class="link" onClick="sortColumn('link_travelingtense')"><?=$this->translate('Travel Intent')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_travelingtense'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
 
                    <th width=""><a href="#" class="link" onClick="sortColumn('link_url')"><?=$this->translate('Url')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_url'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                        
                        <th><a href="#" class="link" onClick="sortColumn('link_status')"><?=$this->translate('Status')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'link_status'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                    </tr>
                    <?
					
						$categoryModel= new LinkCategoryModel();
						$subcatModel= new LinkSubcategoryModel();
						$intentModel= new TravelIntenseModel();
						$travlephaseModel= new TravelphaseModel();
						
                        if(count($this->result)>0){
                         foreach($this->result as $rst){
						 // $linkemodel =new CustomerLinkModel();
						//$linkcount=$linkemodel->GetCustomerLinkCount($rst['link_id']); 
				   ?>

                        <tr class="autoWidth">
                        	<td width=""><?=stripslashes($rst['link_id'])?>
                            <div class="edit-del"><a href="#" onClick="window.location = '<?=$this->baseUrl()?>/admin/link/edit/<?=$rst['link_key_id']?>/<?=$this->page?>';" ><?=$this->translate('Edit')?></a> | <a href="#" onClick="return deleteRow('<?=$this->baseUrl()?>/admin/link/delete/<?=$rst['link_key_id']?>','<?=$this->translate($this->DeleteMess('Link Name', addslashes($rst['link_name'])))?>')" ><?=$this->translate('Delete')?></a></div></td>
                          
                           <td width="12%"><?=stripslashes($rst['link_category'])?>
                            <td width="12%"><?=stripslashes($rst['link_name'])?>
                         
                         <td width="12%"> <?php 
						 /////////////////////To show category from id/////////////////////////
						 if(!empty($rst['link_cat_name'])) {echo $rst['link_cat_name'];}else{ echo "N/A";}
						 ?> </td>
                         
                         <td width="12%"> 
						 <?php 
						 //////////////////////to show sub category  by id //////////////////////
						 if(!empty($rst['link_subcat_name'])) {echo $rst['link_subcat_name'];}else{ echo "N/A";}
						 
						 ?> </td>
                         
                         <td width="12%"> <?php 
						 //////////////to get travlephase from id /////////////////////////////////
							$session = new Zend_Session_Namespace('Site_Lang');
							$lang_id = $session->lang_id;
							if(!empty($rst['link_trip'])):
							 $travelphasewhere= "travelphase_id IN(".$rst['link_trip'].") AND lang_id='".$lang_id."'";
							 $travephase=$travlephaseModel->getTravelphases($travelphasewhere);
							 if(!empty($travephase)){
								 foreach($travephase as $phase)
								 {
									 if($phase['travelphase_name']!=''){echo $phase['travelphase_name']."<br/>";}else{ echo "N/A";}
								 }	 
							 }else{
							 	echo 'N/A';
							 }	 
							 else:
								 echo 'N/A';
							 endif;
							 
						 ?> </td>
                        <td width="12%">
                          <?php 
						///////////////////////to show travel intent from id/////////////////////////
						
							if(!empty($rst['link_travelingtense'])):
							 $intentwhere= "intense_id IN(".$rst['link_travelingtense'].") and lang_id = $lang_id";
							 $travelintent=$intentModel->getTravelIntense($intentwhere);
							 if(!empty($travelintent)){
								 foreach($travelintent as $intent)
								 {
									 if($intent['intense_name']){echo $intent['intense_name']."<br/>";}else{ echo "N/A";}
									 
								 }
							 }else{
							 	echo 'N/A';
							 }	 
							 
							  else:
								 echo 'N/A';
							 endif;
						 ?> </td>
                         
                       <td width="15%"><a href="<?=stripslashes($rst['link_url'])?> "target="_blank"><img src="<?=$this->baseUrl()?>/application_data/common/images/ico-box.gif"/> <?=stripslashes($rst['link_url'])?></a> </td>                   
                          <?php /*?> <td width="23%"><?=stripslashes($rst['link_url'])?>
                          <?php */?> 
                           
                            <td width="12%"><? if($rst['link_status'] == 1) {echo $this->translate('Active');} else {echo $this->translate('Inactive');}?></td>
                        </tr>
                         
                     <?  } 
                       } else {?>
                        <tr>
                        	<td align="center" colspan="3"><?=$this->translate('No record added yet');?></td>
                        </tr>
                   <? }?>
                </table>
                
                <table class="pagination">
                    <tr>
                    	<td width="10%"><?=$this->translate('Results per page')?>:</td>
                        <td><?=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>