<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<?
	//$_SESSION['CKFinder_UserRole'] ='admin';
?>
<script type="text/javascript">

	window.onload = function()
	{
		if(document.getElementById('body')) {
			CKEDITOR.config.filebrowserBrowseUrl = '<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.html';
			CKEDITOR.config.width  = '100%';
			CKEDITOR.config.resize_enabled = true;
			CKEDITOR.config.height = 300;
			if(document.getElementById('body')) {
				CKEDITOR.replace( 'body',  {
					toolbar : 'Full',
					language : 'de',
					skin: 'v2'
				});
			}
		}
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/cms';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" method="post" >
                   
                    <?=$this->form->name?>
                    <label><?=$this->translate('Page Title')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->meta_keywords?>
                    <label><?=$this->translate('Meta keywords')?></label>
                    <div class="clr"></div>
                    
                    
                    <?=$this->form->meta_desc?>
                    <label><?=$this->translate('Meta description')?></label>
                    <div class="clr"></div>
                    
                    
                    <?=$this->form->body?>
                    <label><?=$this->translate('Page Body')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->status?>
                    <label><?=$this->translate('Page Status')?>*</label>
                    <div class="clr"></div>
                    
                    <!--<?//=$this->form->showfooter?>
                    <label><?//=//$this->translate('Show in footer')?></label>
                    <div class="clr"></div>-->
                    
                    
                   
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->placeholder('buttonCaption')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
