<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>



<?
	//$_SESSION['CKFinder_UserRole'] ='admin';
?>
<script type="text/javascript">

    function validateForm()
    {
        //alert("Alerted");
        
        var x1=document.getElementById("event_title").value;
        if (x1=="")
        {
            alert("Title must be filled out*");
            return false;
        }
              
        var x2=document.getElementById("event_description").value;
        if (x2=="")
        {
            alert("Description must be filled out*");
            return false;
        }
        
        var c=1;
        do
        {
            if(document.getElementById("dj"+c))
            {var value = document.getElementById("dj"+c).value;
                if ( value == "")
                {
                    alert("Dj must be filled out*");
                    return false;
                }
            }
            c++;
        }while(c<20);
        
                
        var x3=document.getElementById("entrance_fee").value;
        if (x3=="")
        {
            alert("Entrance fee must be filled out*");
            return false;
        } 
        
        var x4=document.getElementById("total_guests_allowed").value;
        if (x4=="")
        {
            alert("Total guests allowed must be filled out*");
            return false;
        }
        
        
        // Djs
        
        
    }
	window.onload = function()
	{
		
		
	}
	
	function back_to_listing(id)
	{
		window.location = '<?=$this->baseUrl()?>/admin/event/index/id/'+id;
	}
        var count=1;
	function add_dj(c)
        {
            var old_c = c;
            c++;
            count++;
            var html = '';
            html += '<input type="text" id="dj' + count + '" name="dj' + count + '">';
           
            html += '<div id="div' + c + '" class="add-row"><img style="position:relative; left:331px; top:-18px;" onclick="add_dj(' + c + ');" src="<?php echo $this->baseUrl();?>/application_data/common/images/plus.jpg" width="15" height="15"/></div>';
            html += "<label id=lab-"+c+">DJ"+count+"*</label>";
            $("#more_djs").append(html);
            var old_html = '';
            
          if(old_c == 1)
              {
            old_html += '<input type="text" id="dj' + old_c + '" name="dj' + old_c + '">';
            old_html += '<div class="add-row"><img style="position:relative; left:331px; top:-18px;"  onclick="delete_field('+old_c+');" id="'+old_c+'" src="<?php echo $this->baseUrl();?>/application_data/common/images/minus.png" width="20" height="20"/></div>';
            //alert(old_html);
           // $("div"+old_c).update(old_html);
           //var val='div'+old_c;
          // document.getElementById("div"+old_c).innerHTML= old_html;
            old_html += "<label>DJ"+old_c+"*</label>";
            $("#div"+old_c).html(old_html);
            //$("#"+old_c).attr('onclick','').unbind('click');
            }
            else{
              old_html += '<img style="position:relative; left:331px; top:-18px;"  onclick="delete_field('+old_c+');" id="'+old_c+'" src="<?php echo $this->baseUrl();?>/application_data/common/images/minus.png" width="20" height="20"/>';   
              $("#div"+old_c).html(old_html);
           }
            
            
         
         //$("a #1 img").append(old_html);
       }
       
       function delete_field(old_c)
       {
           
           //alert(old_c);
                $("#div"+old_c).remove();
                $("#dj"+old_c).remove();
                $("#lab-"+old_c--).remove();
              //alert("Alertingggggg");
//            if (childId == parentDiv) 
//            {
//            alert("The last DJ cannot be removed.");
//            }
//            else if (document.getElementById(childId)) 
//            {     
              parent.removeChild();
              
//            }
//            else 
//            {
//              alert("Djs have already been removed or does not exist.");
//              return false;
//            }

       }
       

       
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" onsubmit="return validateForm()" method="post" >
                   
                    <div id="title">
                        <?=$this->form->event_title?>
                        <label><?=$this->translate('Event Title')?>*</label>
                        <div class="clr"></div>
                    </div>
                   
                    <?=$this->form->event_description?>
                    <label><?=$this->translate('Event Description')?>*</label>
                    <div class="clr"></div>
                    
                    <div id="div1">                       
                       <input type="text" id="dj1" name="dj1"/>
                       <img onclick="add_dj('1');" src="<?php echo $this->baseUrl();?>/application_data/common/images/plus.jpg" width="20" height="20" />
                       <label>
                          <?=$this->translate('DJ1')?>*
                       </label>
                    </div>
                    <div id="more_djs">
                   
                    </div>
                    
                    <div class="clr"></div>
                    
                    <?=$this->form->entrance_fee?>
                    <label><?=$this->translate('Entrance Fee')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->total_guests_allowed?>
                    <label><?=$this->translate('Total Guests Allowed')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->status?>
                    <label><?=$this->translate('Event status')?>*</label>
                    <div class="clr"></div>
                   
                    <div class="btns">
                        <input name="submit" type="submit" value="<?=$this->translate('Add Event')?>"/>
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing(<?=$this->vid?>);" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
