<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<script type="text/javascript">

	window.onload = function()
	{
		if(document.getElementById('body')) {
			CKEDITOR.config.filebrowserBrowseUrl = '<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.html';
			CKEDITOR.config.width  = '100%';
			CKEDITOR.config.resize_enabled = false;
			CKEDITOR.config.height = 300;
			if(document.getElementById('body')) {
				CKEDITOR.replace( 'body',  {
					toolbar : 'Full',
					language : 'de',
					skin: 'v2'
				});
			}
		}
	}
	
	function back_to_listing(eid)
	{
		window.location = '<?=$this->baseUrl()?>/admin/menu/index/id/'+eid;
	}
	/*var count=1;
	function add_moredj()
        {
         count++;
         var html='';
         html +='<input type="text" name="dj'+count+'">';
         html += '<a onclick="add_moredj();" style="cursor: pointer;">';
         html += '<img src="<?php echo $this->baseUrl();?>/application_data/common/images/plus.jpg" width="15" height="15"/></a>';
         html += "<label>DJ"+count+"*</label>";
         $("#more_djs").append(html);   
      }*/
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td class="blueBg" width="200" height="50">&nbsp;</td>
        <td class="greenBg">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" method="post" >
                
                	 <?=$this->form->p_id?>
                    <label><?=$this->translate('Main Menu')?>*</label>
                    <div class="clr"></div>
                   
                    <?=$this->form->menu_name?>
                    <label><?=$this->translate('Menu Name')?>*</label>
                    <div class="clr"></div>
                   
                   
                    
                    <?=$this->form->menu_status?>
                    <label><?=$this->translate('Menu status')?>*</label>
                    <div class="clr"></div>
                   
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->translate('Edit Menu')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing(<?=$this->eid?>);" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
