<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<script type="text/javascript">

	window.onload = function()
	{
		if(document.getElementById('body')) {
			CKEDITOR.config.filebrowserBrowseUrl = '<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.html';
			CKEDITOR.config.width  = '100%';
			CKEDITOR.config.resize_enabled = false;
			CKEDITOR.config.height = 300;
			if(document.getElementById('body')) {
				CKEDITOR.replace( 'body',  {
					toolbar : 'Full',
					language : 'de',
					skin: 'v2'
				});
			}
		}
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/venue';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td class="blueBg" width="200" height="50">&nbsp;</td>
        <td class="greenBg">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" method="post" >
                   
                   <table width="100%" border="0" cellspacing="2" cellpadding="3">
  <tr>
    <td valign="top"><fieldset>
    <legend><?=$this->translate('Venue Information')?>:</legend><?=$this->form->venue_name?>
                    <label><?=$this->translate('Venue Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->category?>
                    <label><?=$this->translate('Category')?>*</label>
                    <div class="clr"></div></fieldset><br /><fieldset>
    <legend><?=$this->translate('Business Information')?>:</legend><?=$this->form->house_no?>
                    <label><?=$this->translate('House #')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->street?>
                    <label><?=$this->translate('Street')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->city?>
                    <label><?=$this->translate('City')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->post_code?>
                    <label><?=$this->translate('Post Code')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->country?>
                    <label><?=$this->translate('Country')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->telephone?>
                    <label><?=$this->translate('Telephone')?>*</label>
                    <div class="clr"></div>
                    
                   
                    
                   </fieldset><br />
                   <fieldset><legend><?=$this->translate('Venue Status')?>:</legend>
                    <?=$this->form->status?>
                    <label><?=$this->translate('Status')?>*</label>
                    <div class="clr"></div>
                    </fieldset>
                   </td>
    <td valign="top"><fieldset>
    <legend><?=$this->translate('Contact Details')?>:</legend><?=$this->form->first_name?>
                    <label><?=$this->translate('First Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->last_name?>
                    <label><?=$this->translate('Last Name')?>*</label>
                    <div class="clr"></div>
                    
                      <?=$this->form->username?>
                    <label><?=$this->translate('User Name')?>*</label>
                    <div class="clr"></div>
                    
                      <?=$this->form->email?>
                    <label><?=$this->translate('Email')?>*</label>
                    <div class="clr"></div>
                    
                    </fieldset>
                   <br />
                   <fieldset>
    				 <legend><?=$this->translate('Social Media')?>:</legend>
        			 <?=$this->form->facebook?>
                    <label><?=$this->translate('Facebook')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->twitter?>
                    <label><?=$this->translate('Twitter')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->youtube?>
                    <label><?=$this->translate('YouTube')?>*</label>
                    <div class="clr"></div>
                    
                    
                    <?=$this->form->website?>
                    <label><?=$this->translate('Website')?>*</label>
                    <div class="clr"></div>
                    
                    
                    
                   
                    &nbsp;</fieldset>
                    
                   <br />
                    <fieldset>
                    <legend><?=$this->translate('Location')?>:</legend>
                     <?=$this->form->latitude?>
                    <label><?=$this->translate('Latitude')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->longitude?>
                    <label><?=$this->translate('Longitude')?>*</label>
                    <div class="clr"></div>
                    </fieldset>
                    </td>
  </tr>
  
 
</table>
                   
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->placeholder('buttonCaption')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
