<div id="leftCol">
<div class="welcomeBox bg-forgotPass">
    <h2><?=$this->translate('Forgot Password')?></h2>
    <div class="bg-grey">
        <div class="bg-grey2">
            <form method="post" name="forgot_password_form" id="forgot_password_form">
            <input type="hidden" name="submit_forgot" id="submit_forgot" value="1" />
            <ul>
                <li>
                    <label><?=$this->translate('Email')?> <span>*</span></label>
                    <?=$this->form->email;?>
                    <? if(isset($this->errorMsg)) {
                        echo '<div class="errors"><ul><li>'.$this->errorMsg.'</li></ul></div>';
                    }?>
                </li>
                <li class="btn"><input name="submitForgot" value="<?=$this->translate('Retrieve')?>" type="image" src="<?=$this->baseUrl()?>/application_data/common/images/front-end/forget-pswd.gif" /></li>
            </ul>
        </form>
        </div>
    </div>
</div>

</div>