<div id="leftCol">
<div class="welcomeBox bg-forgotPass">
    <h2><?=$this->translate('Free Rgistration')?></h2>
    <div class="bg-grey">
        <div class="bg-grey2">
        <div class="fields">
        
            <form method="post" name="reg_form" id="reg_form">
                 <div class="heading"><?=$this->translate('Location')?> <span>* <?=$this->translate('All fields are required')?></span></div>
                
                <fieldset class="row1">
                <legend>Location Details
                </legend>
                <p >
                <label><?=$this->translate('First Name')?> <span>*</span></label>
                        <?=$this->form->FirstName?>
                </p>
                <p>
                <label><label><?=$this->translate('Last Name')?>*</label>
                     <?=$this->form->LastName?>
                </p>
                 <p><label><?=$this->translate('Business Name')?>*</label>
                    <?=$this->form->BusinessName?>
                    </p>
                    <p> <label><?=$this->translate('Address1')?></label>
                       <?=$this->form->Address1?>
                    </p>
                    <p><label><?=$this->translate('Address2')?></label>
                        <?=$this->form->Address2?>
                        
                    </p>
                    <p>            <label><?=$this->translate('City')?></label>
                          <?=$this->form->City?>
    
                    </p>
                    <p> <label><?=$this->translate('State')?></label>
                        <?=$this->form->State?>
                       
                    </p>
                    <p>
                     <label><?=$this->translate('Postal Code')?></label>
                    <?=$this->form->PostalCode?>
                    </p>
                    <p>
                         <label><?=$this->translate('Country')?></label>
                        <?=$this->form->Country?>
                       
                    </p>
                    <p>
                        <label><?=$this->translate('Phone Number')?></label>
                        <?=$this->form->PhoneNo?>
                        
                    </p>
                   <p>
                    <label><?=$this->translate('Fax Number')?></label>
                                <?=$this->form->FaxNo?>
    
                   </p>
                </fieldset>
                
                 <fieldset class="row1">
            <legend>Login Details
            </legend>
            <p >
                    <label><?=$this->translate('E-Mail')?>:</label>
                    <?=$this->form->Email;?>
                    </p>
                    <p>
                    <label><?=$this->translate('Passwort')?>:</label>
                    <?=$this->form->Password;?>
                    <? if(isset($loginerror->invalidCredentials)&& $loginerror->invalidCredentials!=''){ echo '<div class= "errors"><ul><li>'.$loginerror->invalidCredentials.'</li></ul></div>';}?>
                    </p>
                     <p>     <label><?=$this->translate('Password Confirm')?>*</label>         
                      <?=$this->form->PasswordConfirm?>
              
                         <input type="hidden" name="status" value="0" id=""/>   
                   </p>
                   
            </fieldset>
                <p>
                &nbsp;<button class="button">Save &raquo;</button>
                </p>
           
            </form>
         </div>
        </div>
    </div>
</div>

</div>

