<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?=$this->headTitle()?>
<link href="<?=$this->baseUrl()?>/application_data/common/css/admin-styles.css" rel="stylesheet" type="text/css" />
<!--[if lte IE 6]>
	<link href="<?=$this->baseUrl()?>/application_data/common/css/ie6.css" rel="stylesheet" type="text/css" />
    
    <style type="text/css" media="screen">
        body{behavior:url(css/csshover.htc);}
    </style>
<![endif]-->
</head>

<body class="adminlogin">
<div id="logIn-Area">
<div class="logo"><?=$this->translate("Wspider Web Portal")?></div>
</div>
<div id="loginBox">
	
    <div class="loginForm">
    <?php if(isset($this->message)){ echo '<div class="errors-custom"><ul><li>'.$this->message.'</li></ul></div>';}?>
    	<form method="post">
            <?=$this->form->user_intial?>
            <label><?=$this->translate("User Name")?></label>
            <?=$this->form->password?>
            <label><?=$this->translate("Password")?></label>
            <div class="btn"><input name="" type="submit" value="<?=$this->placeholder('buttonCaption')?>" class="btn" /> </div>
            <a href="<?=$this->baseUrl()?>/admin/login/forgetpassword" title="<?=$this->translate('Forgot password?')?>"><?=$this->translate('Forgot password?')?></a>
        </form>
    </div>
</div>


<div id="ftrLogin"><?=$this->translate("All Rights Reserved with")?> <a href="<?=$this->baseUrl()?>" title="<?=$this->translate('Iceapp')?>"><?=$this->translate('Wspider Web Portal')?></a></div>

</body>
</html>