<div id="leftCol">
<div class="welcomeBox bg-forgotPass">
    <h2><?=$this->translate('For Free site review.')?></h2>
    <div class="bg-grey">
        <div class="bg-grey2">
        <div class="fields">
        
           
                 <div class="heading"> <span>* <?=$this->translate('Thanks to use our site.')?></span></div>
                
                <fieldset class="row1">
                <legend>You have some thing wrong in your submitted data.Please see it and submit once again.
                </legend>
                <p >
                    We have a lot of opportunity which you got it free. 
                <p>
                       kind Regards,
                       Wspider team.
                        
               </p>
                  
                </fieldset>
            
           
         </div>
        </div>
    </div>
</div>

</div>

