<?php 
$id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
if ($this->pageCount): ?>
<div class="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a class="prev" href="<?= $this->url(array('id' => $id,'page' => $this->previous)); ?>">Previous</a>
<?php else: ?>
  <span class="prev"></span>
<?php endif; ?>
<!-- Numbered page links -->
<?php 
	$i=1;
	foreach ($this->pagesInRange as $page): 
   		if ($page != $this->current): ?>
    		<a href="<?= $this->url(array('id' => $id,'page' => $page)); ?>"><?=$page; ?></a><? if($i != $this->pageCount){?>&nbsp;|&nbsp;<? }?>
<?php 	else: ?>
    		<span class="active"><?= $page; ?></span><? if($i != $this->pageCount){?>&nbsp;|&nbsp;<? }?>
<?php 	endif;
	$i++; 
	endforeach; ?>
<!-- Next page link -->

<?php 
	if (isset($this->next)): ?>
  		<a class="next" href="<?= $this->url(array('id' => $id,'page' => $this->next)); ?>">Next</a>
<?php 
	else: ?>  
		<span class="next"></span>
<?php 
	endif; ?>
</div>
<?php 
endif; ?>