

<script>
	function sortColumn(col)
	{ 
		document.getElementById('sort_col').value = col; 
		document.report_list_search.submit();
	}

	function setPaging(obj)
	{
		document.getElementById('perPage').value = obj.value;
		document.report_list.submit();
	}
	
	

</script>
<?
 $session = new Zend_Session_Namespace('report_search');
?>
  <?
	if(isset($this->webId) && !empty($this->webId))
	{
		 $webId=$this->webId;
	}
	else
	{  
		 $webId='';
	}
	
	

?>	    

<form name="report_list" id="report_list" action="<?=$this->baseUrl()?>/admin/reports/index/" method="post">  
   	<input type="hidden" name="perPage" id="perPage" value="<?=$session->perPage?>" />
    <input type="hidden" name="webId" id="webId" value="<?=$webId?>" />

</form>

<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Reports Management')?></h2></td>
                  <td align="right">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            
            <div id="eventListing">
          
            	<form name="report_list_search" id="report_list_search" method="post" action="<?=$this->baseUrl()?>/admin/reports/index/">
                    <input type='hidden' name='sort_col' value='' id='sort_col'>
                    <input type="hidden" name="perPage" id="perPage" value="<?=$session->perPage?>" />
                    <input type="hidden" name="webId" id="webId" value="<?=$webId?>" />
                <table class="pagination">
                    <tr>
                        <td align="right">
                           <?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>  
                        </td>
                    </tr>
                </table>
				<table class="searchBy">
                    <tr>
                        <td width="52%">&nbsp;</td>
                        <td><?=$this->searchform->filters?></td>
                        <td><?=$this->translate('Search By')?></td>
                        <td><span id="val-input"><?=$this->searchform->filterText?></span></td>
                        <td class="btn"><input name="submitAction" type="submit" value="<?=$this->translate('Search')?>" /></td>
                        <td class="btn"><input name="submitAction" type="submit" value="<?=$this->translate('Reset')?>" /></td>
                    </tr>
                </table>
                
                </form>
                
                <table class="listing">
                    <tr class="headings">
                                    
                        <th width=""><a href="#" class="link" onClick="sortColumn('dateTime')"><?=$this->translate('Date')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'dateTime'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                       <th><?=$this->translate('Websites Name')?></th>
 		<th><a href="#" class="link" onClick="sortColumn('webId')"><?=$this->translate('Websites')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'webId'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?></th>
                  
                    <th>Report File</th>
                        
                        <th><a href="#" class="link" onClick="sortColumn('status')"><?=$this->translate('Status')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'status'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?> </th>
                    </tr>
                    <?
					
					
						
                        if(count($this->result)>0){
                         foreach($this->result as $rst){
		  	?>
                  <tr class="autoWidth">
                  <td >

                    <?php 

                    $changDate=explode(' ',$rst['dateTime']);

                    echo $changDate[0];


                    ?>
                  <div class="edit-del"><a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'reports', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a> | 
                                <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'reports', 'action' => 'delete','id' => $rst['id'], 'page' => $this -> page))?>','<?=$this->translate('Are you sure to delete this?')?>')" ><?=$this->translate('Delete') ?></a></div>
                  </td> 
                   <td >  
                    <? 	
                    $webModel = new Application_Model_DbTable_Websites();
                    $webData=$webModel->findName($rst['webId']);
                    
                    ?><a href="<?= $webData['url']?>" class="link" target="_blank"><?= $webData['webTitle']?></a>
                    </td>  
                    <td > <a href="<?= $webData['url']?>" class="link" target="_blank"><?= $webData['url']?></a>
                    </td>   
                      <td>
				<? 
                                $fullfilePath=APPLICATION_PATH.'/../public/frontend/webpdf/'.$rst['filePdf'];
                                $filePdf_path=$this->baseUrl().'/frontend/webpdf/'.$rst['filePdf'];
                                if(file_exists($fullfilePath)){
                                
                                ?> <a href="<?=$filePdf_path?>" target="_blank" title="">yes
                                <img src="<?= $this->baseUrl() ?>/frontend/images/pdf_icon_yes.jpg" />
                                </a>
                                <?
                                }else
                                 echo 'no pdf';
                                                          
                                ?>
                            </td>
                            <!--<td ><?php print date('d M Y', $rst['Created']); ?></td> -->
                            <td width="18%" id="activeDactive<?=$rst['id']?>">
                          
							<?php //print ($rst['status']?$this -> translate('Active'):$this -> translate('Inactive')); ?>
                           
                            <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'reports', 'action' => 'status','id' => $rst['id'], 'page' => $this -> page))?>','<?php echo ('Are you sure to change status?')?>')" >
                           <?php if(!empty($rst['status']) && $rst['status']==1) echo 'Active'; else echo 'Inactive'; ?>
                            </a>
                            </td> 					
                            
            
                            
                        
                          
                      </tr>

                     <? } 
                       } else {?>
                        <tr>
                        	<td align="center" colspan="5"><?=$this->translate('No record added yet');?></td>
                        </tr>
                   <? }?>
                </table>
                
                <table class="pagination">
                    <tr>
                    	<td width="10%"><?=$this->translate('Results per page')?>:</td>
                        <td><?=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>


