<script>
function sortColumn(col) {
	document.getElementById('sort_col').value=col;
	document.brand_list.submit();
}

function setPaging(obj) {
	document.getElementById('perPage').value = obj.value;
	document.brand_perpage.submit();
}

</script>
<? $sessionNamespace = new Zend_Session_Namespace('brand_Search');

?>
<form name="brand_perpage" id="brand_perpage" action="<?=$this->baseUrl()?>/admin/brand" method="post">
	<input type="hidden" name="perpage_field"  id="perpage_field" value=""/>
   	<input type="hidden" name='perPage' id='perPage' value='' />
</form>

<form name="brand_list" id="brand_list" action="<?=$this->baseUrl()?>/admin/brand" method="post">
	<input type="hidden" name="sort_field" id="sort_field" value="" />
    <input type='hidden' name='sort_col' value='' id='sort_col'>
   	<input type="hidden" name="perPage" id="perPage" value="<?=$sessionNamespace->perPage?>" />
</form><?php ?>

<form name="brand_perpage" id="brand_perpage" action="<?=$this->baseUrl()?>/admin/brand/<?=$this->id?>/1" method="post">
   	<input type="hidden" name='perPage' id='perPage' value='' />
</form>

<form name="brand_list" id="brand_list" action="<?=$this->baseUrl()?>/admin/brand/<?=$this->id?>/1" method="post">
    <input type='hidden' name='sort_col' value='' id='sort_col'>
</form>

<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Venue Management')?></h2></td>
                  <td align="right"><a href="<?=$this->url(array('module' => 'admin', 'controller' => 'venue', 'action' => 'add'))?>" class="whiteLink"><strong><?=$this->translate('Add Venue')?></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>

            <div id="eventListing">


                <table class="listing">
                    <tr class="headings">
                       <th width="30%"><div style="width:85px;"><?=$this->translate('Title')?></div> </th>
                        <!--<th><?=$this->translate('Created')?> </th>-->
                        <th><?=$this->translate('Status')?> </th>
                       
                      
                  </tr>
                    <?
                        if(count($this->result)>0){
                        foreach($this->result as $rst) {
		  	?>
                  <tr class="autoWidth">
                            <td>
                               
									<?php print $rst['venue_name']; ?>
                                
                            	<div class="edit-del"><a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'venue', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a> | 
                                <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'venue', 'action' => 'delete','id' => $rst['id'], 'page' => $this -> page))?>','<?=$this->translate('Are you sure to delete this?')?>')" ><?=$this->translate('Delete')?></a> | 
                                <a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'gallery', 'action' => 'index','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Gallery')?></a>
                                |  <a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'event', 'action' => 'index','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Event Management')?></a>
                                </div>
                            </td>

                            <!--<td ><?php print date('d M Y', $rst['Created']); ?></td> -->
                            <td width="18%"><?php print ($rst['status']?$this -> translate('Active'):$this -> translate('Inactive')); ?></td> 
                            
                            
                        
                          
                      </tr>

                     <? }
                    } else {?>
                        <tr>
                        	<td align="center" colspan="8"><?=$this->translate('No record added yet');?></td>
                        </tr>
                   <? }?>
                </table>

                <table class="pagination">
                    <tr>
                    	<!--<td width="10%"><?//=$this->translate('Results per page')?>:</td>-->
                        <td><?  //=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>