<?
	//$_SESSION['CKFinder_UserRole'] ='admin';
?>
<script type="text/javascript">

	window.onload = function()
	{
		
		
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/pages/index/';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="page" action="" method="post"  >
                    
                   
                    <?=$this->form->webId?>
                    <label><?=$this->translate('Site URL')?>*</label>
                    <div class="clr"></div>
                   
                    
                    <?=$this->form->pageUrl?>
                    <label><?=$this->translate('Page URL')?>*</label>
                    <div class="clr"></div>
                   
                    <?=$this->form->pageTitle?>
                    <label><?=$this->translate('Title')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->pageKeywords?>
                    <label><?=$this->translate('Meta Keywords')?></label>
                    <div class="clr"></div>
                    
                     <?=$this->form->pageContent?>
                    <label><?=$this->translate('Meta Description')?></label>
                    <div class="clr"></div>
                    
                   
                  
                    <div class="clr"></div>
                   
                   <input type="hidden" name="status" id="status" value="1" />
                      
                    <div class="btns">
                       
                        <input name="" type="button" value="<?=$this->translate('Cancel')?>" onclick="back_to_listing();" />
                         <input name="" type="submit" value="<?=$this->translate('Save')?>" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
