
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr>
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
               <table class="listing">
                    <tr class="headings">
                                                          
                     <th width="">Bement</th>
                     <th width="">Time</th>
                      <th width="">Value</th>
                     <th>Status</th>
                    </tr>
                    <?
			if(count($this->result)>0){ 
                            
                          //  print_r($this->result);
                         //foreach($this->result as $rst){
		  	?>
                    <tr>
                        
                        <td>Title</td>
                        <td>
                            <p>Expected</p>
                            <hr>
                            <p>Current</p>
                        </td>
                        <td><?=$this->result['pageTitle']?></td>
                        <td> <img src="<?=$this->baseUrl()?>/application_data/common/images/green10.jpeg" alt="sort" />
                            <? //if($this->result['status']==1) echo 'Active'; else echo 'Inactive';?></td>
                    </tr>
                     <tr>
                        
                        <td>Meta Keywords</td>
                        <td><p>Expected</p>
                            <hr>
                            <p>Current</p></td>
                        <td><?=$this->result['pageKeywords']?></td>
                        <td> <img src="<?=$this->baseUrl()?>/application_data/common/images/red10.gif" alt="sort" />
                            <? //if($this->result['status']==1) echo 'Active'; else echo 'Inactive';?></td>
                    </tr>
                     <tr>
                        
                        <td>Meta Description</td>
                        <td><p>Expected</p>
                            <hr>
                            <p>Current</p></td>
                        <td><?=$this->result['pageContent']?></td>
                        <td>
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/green10.jpeg" alt="sort" />
                            <? //if($this->result['status']==1) echo 'Active'; else echo 'Inactive';?></td>
                    </tr>
                    <?
                         }
                       // }
                    ?>
                    <tr>
                        <td colspan="2"><a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a></td>
                        <td colspan="2"> <a href="javascript:void(0);">Check Now</a></td>
                    </tr>
               </table>
                    
            </div>
		</td>
	</tr>
</table>
