
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr>
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
               <table class="listing">
                    <tr class="headings">
                                                          
                     <th width="">Bement</th>
                     <th width="">Time</th>
                      <th width="">Value</th>
                     <th>Status</th>
                    </tr>
                    <?
                    

      
			if(count($this->result)>0){ 
                         //  print_r($this->result);
                         //foreach($this->result as $rst){
 
                  $page =$this->result['pageUrl'];
                  $file_headers = @get_headers($page);
                    
                    if($file_headers[0] == 'HTTP/1.0 404 Not Found') 
                    {
                         $live_title ='NA'; //die($file_headers[0]);
                    }
                    else
                    {
                       
                          // tags
                    $start = '<title>';
                    $end = '<\/title>';

                    // open the file
                    $fp = fopen( $page, 'r' );

                    $cont = "";

                    // read the contents
                    while( !feof( $fp ) ) {
                    $buf = trim( fgets( $fp, 4096 ) );
                    $cont .= $buf;
                    }

                    // get tag contents
                    preg_match( "/$start(.*)$end/s", $cont, $match );

                    // tag contents
                    if(isset($match[ 1 ]) and !empty($match[ 1 ]))
                    $live_title = $match[ 1 ]; 
                    else
                         $live_title ='NA';
                    }
                          
                            
                   $mtags=  @get_meta_tags($page);
		  	?>
                    <tr>
                        
                        <td>Title</td>
                        <td>
                            <p>Expected</p>
                            <hr>
                            <p>Current</p>
                        </td>
                        <td> <p><?=$this->result['pageTitle']?>
                            </p>
                            <hr>
                            <p> 
                                <?=$live_title?>
                            </p>
                        </td>
                        <td> 
                            <? if(strcmp($live_title, $this->result['pageTitle'])==0) {?>
                            
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/green10.jpeg" alt="sort" />
                            <? } else {?>
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/red10.gif" alt="sort" />
                            <? } ?>
                            
                        </td>
                    </tr>
                     <tr>
                        
                        <td>Meta Keywords</td>
                        <td><p>Expected</p>
                            <hr>
                            <p>Current</p></td>
                        <td><?=$this->result['pageKeywords']?>
                          <hr>     <p> <? //if($this->result['reportCheckStatus']!='')?>
                                <? if(isset($mtags['keywords'])) echo $mtags['keywords'];?>
                            </p>
                        </td>
                        <td>
                            
                             <? if( isset($mtags['keywords']) and strcmp($mtags['keywords'], $this->result['pageKeywords'])==0  ) {?>
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/green10.jpeg" alt="sort" />
                            <? } else {?>
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/red10.gif" alt="sort" />
                            <? } ?>
                        </td>
                    </tr>
                     <tr>
                        
                        <td>Meta Description</td>
                        <td><p>Expected</p>
                            <hr>
                            <p>Current</p></td>
                        <td><?=$this->result['pageContent']?>
                          <hr>  <p>
                              <? if(isset($mtags['description'])) echo $mtags['description'];?>
                                    
                         </p>
                        </td>
                        <td>
                            <? 
                            if( isset($mtags['description']) and (strncasecmp($mtags['description'], $this->result['pageContent'],50)) == 0 ) {?>
                            
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/green10.jpeg" alt="sort" />
                            <? } else {?>
                            <img src="<?=$this->baseUrl()?>/application_data/common/images/red10.gif" alt="sort" />
                            <? } ?>
                        </td>
                    </tr>
                    <?
                         }
                       // }
                    ?>
                    <tr>
                        <td colspan="2"><a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'edit','id' => $this->result['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a></td>
                        <td colspan="2">  <a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'reportstatus','id' => $this->result['id'], 'page' => $this -> page))?>';" >Check Now</a></td>
                    </tr>
               </table>
                    
            </div>
		</td>
	</tr>
</table>
