<script type="text/javascript">

	
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/pages';
	}
	
</script>

<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td class="blueBg" width="200" height="50">&nbsp;</td>
        <td class="greenBg">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="page" action="" method="post"  >
                  
                    <?=$this->form->webId?>
                    <label><?=$this->translate('Site URL')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->pageUrl?>
                    <label><?=$this->translate('Page URL')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->pageTitle?>
                    <label><?=$this->translate('Title')?>*</label>
                    <div class="clr"></div>
                                        
                    <?=$this->form->pageKeywords?>
                    <label><?=$this->translate('Meta Keywords')?></label>
                    <div class="clr"></div>
                    
                     <?=$this->form->pageContent?>
                    <label><?=$this->translate('Meta Description')?></label>
                    <div class="clr"></div>
                    
                     <?=$this->form->status?>
                    <label><?=$this->translate('Page Status')?></label>
                    <div class="clr"></div>
                    <?php $rs = $this->res; ?>
                   
                  
                   
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->placeholder('buttonCaption')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
