
<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Page Management')?></h2></td>
                  <td align="right"><a href="<?=$this->url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'add'))?>" class="whiteLink"><strong><?=$this->translate('Add Page')?></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            
            <div id="eventListing">
           
          
        
                
                <table class="listing">
                    <tr class="headings">
                                                          
                     <th width=""><?=$this->translate('Pages')?></th>
                     <th width="">Action</th>
                     <th>Status</th>
                     <th>Active&nbsp;/&nbsp;Inactive</th>
                    </tr>
                    <?
			if(count($this->result)>0){
                         foreach($this->result as $rst){
		  	?>
                  <tr class="autoWidth">
                 
                  <td >
                <a href="<?=$rst['pageUrl']?>" target="_blank" class="link"><?=$rst['pageUrl']?></a>
                  <?php //print $rst['pageTitle']; ?>
                 
                  </td> 
                <td>
                <div class="">
                <a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a>
                | 
                <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'delete','id' => $rst['id'], 'page' => $this -> page))?>','<?php echo ('Are you sure you want to delete this page.?')?>')" ><?=$this->translate('Delete')?></a>
                |
                 <a href="javascript:void(0);" onclick="window.location ='<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'detail','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Detail')?></a>
                </div>
                </td> 
                <td>
                    <? 
                    
                    $filename = $rst['pageUrl'];
                    
                    $file_headers = @get_headers($filename);
                   
                    if($file_headers[0] == 'HTTP/1.0 404 Not Found') {
                    $live_title ='NA'; //die($file_headers[0]);
                    }
                    else 
                    {
                    

                        // tags
                        $start = '<title>';
                        $end = '<\/title>';

                        // open the file
                        $fp = fopen( $filename, 'r' );

                        $cont = "";

                        // read the contents
                        while( !feof( $fp ) ) {
                        $buf = trim( fgets( $fp, 4096 ) );
                        $cont .= $buf;
                        }

                        // get tag contents
                        preg_match( "/$start(.*)$end/s", $cont, $match );

                        // tag contents

                        $live_title = @$match[ 1 ]; 
                   
                        
                    }


                   
                   $mtags=  @get_meta_tags($filename);
                  
                if(count($mtags)>0)  
                {   
                    $objModel = new Application_Model_DbTable_Pages();
                    $greenRed= $objModel->getCount($where="reportStatus >2 and status=1 and id=".$rst['id']);

                    if(strcmp($live_title, $rst['pageTitle'])==0 and strcmp($mtags['keywords'], $rst['pageKeywords'])==0 and ( (strncasecmp($mtags['description'], $rst['pageContent'],50)) == 0))
                    {
                    ?>

                    <img src="<?=$this->baseUrl()?>/application_data/common/images/green10.jpeg" alt="sort" />
                    
                   
                    <?
                    }
                    else
                    {
                    ?>
                   <img src="<?=$this->baseUrl()?>/application_data/common/images/red10.gif" alt="sort" />
                   
                   
                    <?
                    }
                }else
                    {
                    ?>
                      
                   <img src="<?=$this->baseUrl()?>/application_data/common/images/red10.gif" alt="sort" />
                   
                   
                    <?
                    }
                    ?>
                </td>
                            <td width="18%" id="activeDactive<?=$rst['id']?>">
                            <?php //print ($rst['status']?$this -> translate('Active'):$this -> translate('Inactive')); ?>
                           
                            <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'status','id' => $rst['id'], 'page' => $this -> page))?>','<?php echo ('Are you sure to change status?')?>')" >
                            <?php print ($rst['status']?$this -> translate('Active'):$this -> translate('Inactive')); ?>
                            </a>
                            </td> 					
                         
                      </tr>

                     <? } 
                       } else {?>
                        <tr>
                        	<td align="center" colspan="6"><?=$this->translate('No record added yet');?></td>
                        </tr>
                   <? }?>
                </table>
                
                <table class="pagination">
                    <tr>
                    	<td width="10%"><?=$this->translate('Results per page')?>:</td>
                        <td><? //=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?//=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                            <?=$this->paginationControl($this->paginator,'Sliding','paginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>


