
<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Page Management')?></h2></td>
                  <td align="right"><a href="<?=$this->url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'add'))?>" class="whiteLink"><strong><?=$this->translate('Add Page')?></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            
            <div id="eventListing">
           
          
        
                
                <table class="listing">
                    <tr class="headings">
                                                          
                     <th width=""><?=$this->translate('Pages')?></th>
                     <th width="">Action</th>
                     <th>Status</th>
                    </tr>
                    <?
			if(count($this->result)>0){
                         foreach($this->result as $rst){
		  	?>
                  <tr class="autoWidth">
                 
                  <td >
                <a href="<?=$rst['pageUrl']?>" target="_blank" class="link"><?=$rst['pageUrl']?></a>
                  <?php //print $rst['pageTitle']; ?>
                 
                  </td> 
                <td>
                <div class="">
                <a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a>
                | 
                <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'delete','id' => $rst['id'], 'page' => $this -> page))?>','<?php echo ('Are you sure you want to delete this page.?')?>')" ><?=$this->translate('Delete')?></a>
                |
                 <a href="javascript:void(0);" onclick="window.location ='<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'detail','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Detail')?></a>
                </div>
                </td>       
                            <td width="18%" id="activeDactive<?=$rst['id']?>">
                            <?php //print ($rst['status']?$this -> translate('Active'):$this -> translate('Inactive')); ?>
                           
                            <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'status','id' => $rst['id'], 'page' => $this -> page))?>','<?php echo ('Are you sure to change status?')?>')" >
                            <?php print ($rst['status']?$this -> translate('Active'):$this -> translate('Inactive')); ?>
                            </a>
                            </td> 					
                         
                      </tr>

                     <? } 
                       } else {?>
                        <tr>
                        	<td align="center" colspan="6"><?=$this->translate('No record added yet');?></td>
                        </tr>
                   <? }?>
                </table>
                
                <table class="pagination">
                    <tr>
                    	<td width="10%"><?=$this->translate('Results per page')?>:</td>
                        <td><? //=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?//=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                            <?=$this->paginationControl($this->paginator,'Sliding','paginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>


