<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<script type="text/javascript">

	window.onload = function()
	{
		if(document.getElementById('body')) {
			CKEDITOR.config.filebrowserBrowseUrl = '<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.html';
			CKEDITOR.config.width  = '100%';
			CKEDITOR.config.resize_enabled = false;
			CKEDITOR.config.height = 300;
			if(document.getElementById('body')) {
				CKEDITOR.replace( 'body',  {
					toolbar : 'Full',
					language : 'de',
					skin: 'v2'
				});
			}
		}
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/customer';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td class="blueBg" width="200" height="50">&nbsp;</td>
        <td class="greenBg">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" method="post" >
                   
                   <table width="100%" border="0" cellspacing="2" cellpadding="3">
  <tr>
    <td valign="top">
                   <fieldset>
    <legend><?=$this->translate('Customer Information')?>:</legend><?=$this->form->FirstName?>
                    <label><?=$this->translate('First Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->LastName?>
                    <label><?=$this->translate('Last Name')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->BusinessName?>
                    <label><?=$this->translate('Business Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->PhoneNo?>
                    <label><?=$this->translate('Phone No')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->FaxNo?>
                    <label><?=$this->translate('Fax No')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->Address1?>
                    <label><?=$this->translate('Address1')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->Address2?>
                    <label><?=$this->translate('Address2')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->PostalCode?>
                    <label><?=$this->translate('Postal Code')?>*</label>
                    <div class="clr"></div>
                     <?=$this->form->Country?>
                    <label><?=$this->translate('Country')?>*</label>
                    <div class="clr"></div>
                     <?=$this->form->State?>
                    <label><?=$this->translate('State')?>*</label>
                    <div class="clr"></div>
                     <?=$this->form->City?>
                    <label><?=$this->translate('City')?>*</label>
                    <div class="clr"></div>
                     
                    
                   </fieldset>
                   </td>
    <td valign="top"><fieldset>
    <legend><?=$this->translate('Login Details')?>:</legend><?=$this->form->Email?>
                    <label><?=$this->translate('Email')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->Password?>
                    <label><?=$this->translate('Password')?>*</label>
                    <div class="clr"></div>
                    
                                                             
                    </fieldset>
                   <br />
                   
                    <fieldset><legend><?=$this->translate('Customer Status')?>:</legend>
                    <?=$this->form->status?>
                    <label><?=$this->translate('Status')?>*</label>
                    <div class="clr"></div>
                    </fieldset>
                   <br />
                    
                    </td>
  </tr>
  
 
</table>
                   
                    <div class="btns">
                    
                        <input name="" type="submit" value="<?=$this->placeholder('buttonCaption')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
