<div id="header">
    <h1><a href="<?=$this -> url(array('module' => 'admin','controller' => 'headmenu', 'action' => 'menu', 'mainmenu' => 'index', 'submenu' => '1'))?>">
    <?=$this->translate('Wspider Web Portal')?></a></h1>
    <!--<div class="language"><? //$this->getSelectedLanguage();?></div>-->
    <div class="hdr-links">
    <a href="<?=$this -> url(array('module' => 'admin','controller' => 'headmenu', 'action' => 'menu','mainmenu' => 'index', 'submenu' => '1'))?>">Home</a> |
    
    <a href="<?=$this -> url(array('module' => 'admin','controller' => 'login','action' => 'logout'))?>">Logout</a> 
    </div>
</div>