<?php
	$moduleName = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
	
	$storage = new Zend_Auth_Storage_Session();
	$storageData = $storage->read();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="shortcut icon" type="image/x-icon" href="<?= $this -> baseUrl()?>/frontend/images/favicon.ico">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?=$this->headTitle()?>
<link rel="shortcut icon" href="<?=$this->baseUrl()?>/application_data/common/images/favicon.ico" type="image/x-icon" />
<link href="<?=$this->baseUrl()?>/application_data/common/css/admin-styles.css" rel="stylesheet" type="text/css" />
<link href="<?=$this->baseUrl()?>/application_data/common/highslides/highslide/highslide.css" rel="stylesheet" type="text/css" />
<link href="<?=$this->baseUrl()?>/application_data/common/css/developer-styles.css" rel="stylesheet" type="text/css" />
<script language="javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ua.js"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/js/mootools.v1.11.js" language="javascript"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/highslides/highslide/highslide-with-html.js" language="javascript"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/js/nogray_time_picker.js" language="javascript"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/js/calendar.js" language="javascript"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/js/calendar-en.js" language="javascript"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/js/calendar-setup.js" language="javascript"></script>
<script src="<?=$this->baseUrl()?>/application_data/common/js/common.js" language="javascript"></script>
<script language="javascript" src="<?=$this->baseUrl()?>/application_data/common/js/image_pop/tool_tip_pointer.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/image_pop/wz_tooltip.js"></script>
<!--[if lte IE 6]>
	<link href="<?=$this->baseUrl()?>/application_data/common/css/admin-ie6.css" rel="stylesheet" type="text/css" />
    
    <style type="text/css" media="screen">
        body{behavior:url(<?=$this->baseUrl()?>/application_data/common/css/csshover.htc);}
    </style>
<![endif]-->
<!--[if gte IE 7]>
	<link href="<?=$this->baseUrl()?>/application_data/common/css/ie7.css" rel="stylesheet" type="text/css" />
    
 <![endif]-->
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/js/jquery-ui.min.js"></script>
<script>
	function makePopup (id) 
	{
			xval = 10;yval = 20;
			var txt1 = "<table cellpadding='0' cellspacing='0' border='5' bordercolordark='#666666'  bordercolorlight='#999999'>";
			txt1 += "<tr>";
			txt1 +=	"<td><img src='"+id+"' width='100%' height='100%' /></td>";
			txt1 +=	"</tr>";
			txt1 +=	"</table>";
			return txt1;
	}

</script>
</head>
<? 
			$sessionNamespace = new Zend_Session_Namespace('Admin_Menu');
?>
<body>
<?php
			$errorMessage = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->getMessages();
			if(!empty($errorMessage))
			{
				if($errorMessage[0] == "fale" || $errorMessage[0] == "success")
				{
				?>
              <div id="successme" align="center"><?=$errorMessage[1]?></div>
                 <script language="javascript">	
				  	
					 $("#successme").fadeOut(10000);  
					 //  $("#success-message").slideUp();  
   					 $("#successme").fadeOut("slow", function() {  
					 $("#successme").slideUp(); 
   					});  
				
				 </script>
				
				<?
                ///	echo '<div class= "errors"><ul><li>'.$errorMessage[1].'</li></ul></div>';
				
                }
			}
		?>
<div id="container">
	     
	<?=$this->render('header.phtml')?>
    <ul id="topNav">
	<? $menuDetail = $this->getTopMenu();
		//print_r($menuDetail); die;
		
		foreach($menuDetail as $row)
		{
		  ?>
    		 <li class="subMenu <? if(isset($sessionNamespace->keyValue)){
                     if($sessionNamespace->keyValue == $row['modules_name']){?>active<? }}?>">
                     <? //=$row['modules_name'].$row['action']
                       if($row['action']!='index')
                       {
                     ?>
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'headmenu','action'=>'menu','mainmenu' => $row['modules_name'], 'submenu' => $row['modules_id'], 'target' => $row['action']));?>"><?=$this->translate($row['module_actual_name'])?>
                        </a>
                     <?
                       }else
                       {
                      ?>
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'headmenu','action'=>'menu','mainmenu' => $row['modules_name'], 'submenu' => $row['modules_id']));?>"><?=$this->translate($row['module_actual_name'])?>
                        </a>
                     <?
                       }
                     ?>
            
             
            <? $subMenuDetails = $this->getSubMenu($row['modules_id']);
				
				
				if(!empty($subMenuDetails)){?>
                <ul>
			<?		foreach($subMenuDetails as $rows)
					{
			?>	
                        <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'headmenu','action'=>'menu','mainmenu' => $row['modules_name'], 'submenu' => $rows['parent_id'], 'target' => $rows['action']));?>"><?=$this->translate($rows['module_actual_name'])?></a></li>
            <?	
					}
			?>    	
                </ul>
            <?  }
			?>
            
            
            
            
            </li>
            
     <? }?>
             <li class="subMenu" style="float:right">
              <a href="<?=$this -> url(array('module' => 'admin','controller' => 'user','action' => 'edit','id' => '1'))?>">My Account</a>
            </li>
    </ul>
    <div class="clr"></div>
    
     <?=$this->layout()->content?>
</div>

</body>
</html>