<? 
$sessionNamespace = new Zend_Session_Namespace('Site_Lang');
?>

<div class="language-select">
<? if(isset($sessionNamespace->site_id)){
		$site = $sessionNamespace->site_id;
   } else {
   		$site = 1;
   }
   $countryModel = new CountryModel();
   $countryData = $countryModel->fetchRow("country_id = '".$site."'");
   $languages = $this->getSiteLanguages($site);
   foreach($languages as $result) {
?>    
		<a href="<?=$this->baseUrl()?>/admin/home/sitelanguages/<?=$result['language_id']?>" class="active <? if(isset($sessionNamespace->lang_id)){ if($sessionNamespace->lang_id == $result['language_id']) {?>activeLanguage<? }}?>">&nbsp;&nbsp;<?=$result['language_name']?></a>
<? }?>
</div>