<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<?
	//$_SESSION['CKFinder_UserRole'] ='admin';
?>
<script type="text/javascript">

	window.onload = function()
	{
		
		
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/category';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" method="post" enctype="multipart/form-data" >
                   
                    <? //=$this->form->parent_id?>
                    <label><? //=$this->translate('Parent category')?></label>
                   
                   
                    <?=$this->form->name?>
                    <label><?=$this->translate('Category Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->status?>
                    <label><?=$this->translate('Category status')?>*</label>
                    <div class="clr"></div>
                    
                    <img src="<?= $this->baseUrl()?>/<?= $this->result['icon'] ?>" height="30" width="30" />
                     <?=$this->form->icon?>
                    <label><?=$this->translate('Category icon')?>*</label>
                    <div class="clr"></div>
                   
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->translate('Add Category')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
