<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<?
	//$_SESSION['CKFinder_UserRole'] ='admin';
?>
<script type="text/javascript">

	window.onload = function(vid)
	{
		
		
	}
	
	function back_to_listing(vid)
	{
		window.location = '<?=$this->baseUrl()?>/admin/gallery/index/id/'+vid;
	}
	

 </script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <div style="width:250px;"> 
                 <?php
				   $typeImage = $typeVideo = '';
				   if ($this -> gType == 'image'){
					   $typeImage = 'checked="checked"';
					   $label = 'Image';
					   $element = 'image';
				   }else{
					   $typeVideo = 'checked="checked"';
					   $label = 'Video';
					   $element = 'video';
				   }
				 ?>
                 <input style="width:auto;" type="radio" name="product" <?php print $typeImage?> value="1" onclick="window.location='<?=$this->url(array('module' => 'admin', 'controller' => 'gallery', 'action' => 'add', 'id' => $this -> vid))?>'"/> <?=$this->translate('Image')?>&nbsp;&nbsp;
<input type="radio" style="width:auto;" <?php print $typeVideo?> name="product" value="2" onclick="window.location='<?=$this->url(array('module' => 'admin', 'controller' => 'gallery', 'action' => 'add', 'id' => $this -> vid))?>?action=video'"/> <?=$this->translate('Video')?></div>
                <form name="adddisease" action="" method="post"  enctype="multipart/form-data">
             
    			  <?=$this->form->venue_id?>
                  <div id="main" ><?=$this->form->{$element}?>
                    <label><?=$this->translate($label)?>*</label>
                    <div class="clr"></div></div>
                    
                    <?=$this->form->status?>
                    <label><?=$this->translate('Status')?>*</label>
                    <div class="clr"></div>
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->translate('Add Gallery')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing(<?=$this ->vid ?>)" />
                    </div>
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
