<script>
function sortColumn(col) {
	document.getElementById('sort_col').value=col;
	document.brand_list.submit();
}

function setPaging(obj) {
	document.getElementById('perPage').value = obj.value;
	document.brand_perpage.submit();
}

</script>
<script type="text/javascript">
    // Apply the Highslide settings
    hs.graphicsDir = '<?=$this->baseUrl()?>/application_data/common/highslides/highslide/graphics/';
    hs.outlineType = 'rounded-white';
    hs.outlineWhileAnimating = true;
</script>

<? $sessionNamespace = new Zend_Session_Namespace('brand_Search');

?>
<form name="brand_perpage" id="brand_perpage" action="<?=$this->baseUrl()?>/admin/gallery" method="post">
	<input type="hidden" name="perpage_field"  id="perpage_field" value=""/>
   	<input type="hidden" name='perPage' id='perPage' value='' />
</form>

<form name="brand_list" id="brand_list" action="<?=$this->baseUrl()?>/admin/gallery" method="post">
	<input type="hidden" name="sort_field" id="sort_field" value="" />
    <input type='hidden' name='sort_col' value='' id='sort_col'>
   	<input type="hidden" name="perPage" id="perPage" value="<?=$sessionNamespace->perPage?>" />
</form><?php ?>

<form name="brand_perpage" id="brand_perpage" action="<?=$this->baseUrl()?>/admin/gallery/<?=$this->id?>/1" method="post">
   	<input type="hidden" name='perPage' id='perPage' value='' />
</form>

<form name="brand_list" id="brand_list" action="<?=$this->baseUrl()?>/admin/gallery/<?=$this->id?>/1" method="post">
    <input type='hidden' name='sort_col' value='' id='sort_col'>
</form>

<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Gallery Management')?></h2></td>
                  <td align="right"><a href="<?=$this->url(array('module' => 'admin', 'controller' => 'gallery', 'action' => 'add'))?>" class="whiteLink"><strong><?=$this->translate('Add Gallery')?></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>

            <div id="eventListing">


                <table class="listing">
                    <tr class="headings">
                       <th width="30%"><div style="width:85px;"><?=$this->translate('Gallery')?></div> </th>
                        <!--<th><?=$this->translate('Created')?> </th>-->
                  </tr>
                  </table>
                 <table class="listing gallary-listing">
                  <tr class="autoWidth">
                    <?
                        if(count($this->result)>0){
							$cnt=0;
                        foreach($this->result as $rst) {$cnt=$cnt+1;
		  	?>
                  
                            <td>
                            <?php if(!empty($rst['image'])){?>
                           <a id="thumb1" href="<?php echo $this->baseURL();?>/gallery/<?php echo  $rst['image']; ?>" class="highslide" onclick="return hs.expand(this, { headingText: 'Gallery', creditsText : '' })">
	<img src="<?php echo $this->baseURL();?>/gallery/thumbnail/<?php echo  $rst['image']; ?>" /></a>
                               
                                <?php
							}else{
								if(!empty($rst['video'])){
								 $cny=explode('embed/', $rst['video']);
								  $youtubeid=explode('?',$cny[1]);
								   
								?>
								<a href="<?php echo  $rst['video']; ?>" onclick="return hs.htmlExpand(this, {creditsText : '', headingText: 'Video Gallery', objectType: 'iframe', width: 480, height: 385, 
		allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', 
		preserveContent: false, objectLoadTime: 'after'})"
        class="highslide"><img src="http://img.youtube.com/vi/<?php echo $youtubeid[0];?>/2.jpg" height="75" width="85" /></a>
								<?php
								}
								}
								?>
                            	<div class="edit-del"><a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'gallery', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a> | 
                                <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'gallery', 'action' => 'delete','id' => $rst['id'],'vid'=> $rst['venue_id'] , 'page' => $this -> page))?>','<?=$this->translate('Are you sure to delete this?')?>')" ><?=$this->translate('Delete')?></a></div>
                            

                            <!--<td ><?php print date('d M Y', $rst['Created']); ?></td> -->
                            
                            </td>
                          
                     <? if($cnt%5==0){echo '</tr><tr>';}}
                    } else {?>
                        
                        	<td><?=$this->translate('No record added yet');?></td>
                       
                   <? }?> </tr>
                </table>

                <table class="pagination">
                    <tr>
                    	<!--<td width="10%"><?//=$this->translate('Results per page')?>:</td>-->
                        <td><?  //=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>