<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>


<?
	//$_SESSION['CKFinder_UserRole'] ='admin';
?>
<script type="text/javascript">

	window.onload = function()
	{
		
		
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/customer';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td bgcolor="#eae2c9" width="200" height="50">&nbsp;</td>
        <td bgcolor="#eae2c9">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                
                <form name="adddisease" action="" method="post" >
                <table width="100%" border="0" cellspacing="2" cellpadding="3">
  <tr>
    <td valign="top"><fieldset>
    <legend><?=$this->translate('Location')?>:</legend><?=$this->form->FirstName?>
                    <label><?=$this->translate('First Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->LastName?>
                    <label><?=$this->translate('Last Name')?>*</label>
                    <div class="clr"></div>
                    <div class="clr"></div>
                    <div class="clr"></div>
                    <?=$this->form->BusinessName?>
                    <label><?=$this->translate('Business Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->Address1?>
                    <label><?=$this->translate('Address1')?></label>
                    <div class="clr"></div>
                    
                     <?=$this->form->Address2?>
                    <label><?=$this->translate('Address2')?></label>
                    <div class="clr"></div>
                    <?=$this->form->City?>
                    <label><?=$this->translate('City')?></label>
                    <div class="clr"></div>
                      <?=$this->form->State?>
                    <label><?=$this->translate('State')?></label>
                    <div class="clr"></div>
                     
                     <?=$this->form->PostalCode?>
                    <label><?=$this->translate('Postal Code')?></label>
                    <div class="clr"></div>
                      <?=$this->form->Country?>
                    <label><?=$this->translate('Country')?></label>
                    <div class="clr"></div>
                    <div class="clr"></div>
                    <div class="clr"></div>
                    <?=$this->form->PhoneNo?>
                    <label><?=$this->translate('Phone Number')?></label>
                    <div class="clr"></div>
                    <?=$this->form->FaxNo?>
                    <label><?=$this->translate('Fax Number')?></label>
                    <div class="clr"></div>
                    
                    
                   </fieldset><br />
                   
                   </td>
    <td valign="top"><fieldset>
    <legend><?=$this->translate('Login')?>:</legend><?=$this->form->Email?>
                    <label><?=$this->translate('Email')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->Password?>
                    <label><?=$this->translate('Password')?></label>
                    <div class="clr"></div>
                    
                      <?=$this->form->PasswordConfirm?>
                    <label><?=$this->translate('Password Confirm')?></label>
                    <div class="clr"></div>
                                        
                    </fieldset>
                    <br />
                  
                    
                   
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td width="50%"> <?php if(!empty($this->forCutomerWeb)){?>
                    <fieldset>
                    <legend><?php echo ('Select websites for customer')?>:</legend>
                    <div id="pagination">
                    <div style="height:270px; vertical-align:top; overflow:auto">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td class="navigatepage" style="text-align:right;">&lt;&lt;<a  href="javascript:void(0)"> Previous</a> &nbsp;&nbsp;<?php echo "1 of ".ceil(($this->total) / 8)." pages";?>&nbsp;&nbsp;<?php if(($this->total)>8){?><a href="javascript:void(0)" onclick="javascript:callajax(2);"> Next </a>  &gt;&gt;<?php }else{?> <a  href="javascript:void(0)">Next</a> &gt;&gt;<?php }?></td>
                    </tr>
                    </table><table width="100%" cellpadding="0" cellspacing="0">
                    
                    <?php   $i=0;
                    foreach($this->forCutomerWeb as $rst) {?>
                    <tr class="autoWidth"><td width="33%">
                    <input type="checkbox" name="websites[]" value="<?php print $rst['id']; ?>" /> 
                    <?php print $rst['url']; $i++; ?>
                    </td></tr>
                    <?php 
                    
                    }
                    ?>
                    
                    
                    </table>
                    </div>
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td class="navigatepage" style="text-align:right;">&lt;&lt;<a href="#"> Previous</a> &nbsp;&nbsp;<?php echo "1 of ".ceil(($this->total) / 10)." pages";?>&nbsp;&nbsp;<?php if(($this->total)>10){?><a href="#" onclick="javascript:callajax(2);"> Next </a>  &gt;&gt;<?php }else{?> <a  href="#">Next</a> &gt;&gt;<?php }?></td>
                    </tr>
                    </table> 
                    
                    </div>
                    </fieldset>
                    <?php }?></td>
                    
                    </tr>
                    </table>
                    <input type="hidden" name="lecturearrayval" id="lecturearrayval" value="" />
                    <input type="hidden" name="status" id="status" value="1" />
                    <div class="btns">
                       
                        <input name="" type="button" value="<?=$this->translate('Cancel')?>" onclick="back_to_listing();" />
                         <input name="" type="submit" value="<?=$this->translate('Save')?>" />
                    </div>
                    </td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
<script type="text/javascript">
var myData = "name=William Adama&alias=Husker&job=Commander of the Colonial Fleet";
function callajax(id){ 
var myCars=new Array();
var boxes = document.getElementsByName('websites[]');
var j=0;
for (i = 0; i < boxes.length; i++){
	
	if(boxes[i].checked == true){
		myCars[j]=boxes[i].value;
		j++;
      // concatval.value=concatval.value+","+boxes[i].value;
	  // alert(concatval.value);
    }

	
	}
	if(myCars.length>0){
		var lecturearr=document.getElementById('lecturearrayval');
		if(lecturearr.value==""){
			lecturearr.value=myCars.join(",");
			}else{
				lecturearr.value=lecturearr.value+','+myCars.join(",");
				}
//alert(lecturearr.value);		//document.getElementById('lecturearrayval').value=myCars.join(",");
		
		}
//alert(myCars.join(","));
	
				
				
$.ajax({

            type: "POST",

            url: "<?php echo $this -> baseUrl()?>/admin/customer/allwebpaging/id/"+id+"/csid/0",

            data: "websites="+document.getElementById('lecturearrayval').value,
            success: function(responseText) {
				//alert(responseText);
				$("pagination").html(responseText);
				document.getElementById("pagination").innerHTML=responseText;
            },

            error: function() {

                // alert("AJAX call an epic failure");

            }

        });

        return false;
}
</script>
