<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/application_data/common/js/ckfinder/ckfinder.js"></script>

<script type="text/javascript">

	window.onload = function()
	{
		
		
	}
	
	function back_to_listing()
	{
		window.location = '<?=$this->baseUrl()?>/admin/customer';
	}
	
</script>
<link rel="stylesheet" href="<?=$this->baseUrl()?>/application_data/common/css/CalendarControl.css" />
<span id="temp_span" style="display:none" ></span>
<table id="twoCols">
	<tr>
    	<td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
       	<td class="blueBg" width="200" height="50">&nbsp;</td>
        <td class="greenBg">
           	<table width="100%">
               	<tr>
                   	<td><h2><?=$this->placeholder('heading')?></h2></td>
                    <td align="right"><a href="#" class="whiteLink"><strong></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
      	<td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
    	<?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
           	<div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            <div id="eventListing">
            
                <div id="addEvent">
                <form name="adddisease" action="" method="post" >
                   
                   <table width="100%" border="0" cellspacing="2" cellpadding="3">
  <tr>
    <td valign="top">
                   <fieldset>
    <legend><?=$this->translate('Customer Information')?>:</legend><?=$this->form->FirstName?>
                    <label><?=$this->translate('First Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->LastName?>
                    <label><?=$this->translate('Last Name')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->BusinessName?>
                    <label><?=$this->translate('Business Name')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->PhoneNo?>
                    <label><?=$this->translate('Phone No')?>*</label>
                    <div class="clr"></div>
                    <?=$this->form->FaxNo?>
                    <label><?=$this->translate('Fax No')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->Address1?>
                    <label><?=$this->translate('Address1')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->Address2?>
                    <label><?=$this->translate('Address2')?>*</label>
                    <div class="clr"></div>
                    
                     <?=$this->form->PostalCode?>
                    <label><?=$this->translate('Postal Code')?>*</label>
                    <div class="clr"></div>
                     <?=$this->form->Country?>
                    <label><?=$this->translate('Country')?>*</label>
                    <div class="clr"></div>
                     <?=$this->form->State?>
                    <label><?=$this->translate('State')?>*</label>
                    <div class="clr"></div>
                     <?=$this->form->City?>
                    <label><?=$this->translate('City')?>*</label>
                    <div class="clr"></div>
                     
                    
                   </fieldset>
                   </td>
    <td valign="top"><fieldset>
    <legend><?=$this->translate('Login Details')?>:</legend><?=$this->form->Email?>
                    <label><?=$this->translate('Email')?>*</label>
                    <div class="clr"></div>
                    
                    <?=$this->form->Password?>
                    <label><?=$this->translate('Password')?>*</label>
                    <div class="clr"></div>
                    
                                                             
                    </fieldset>
                   <br />
                   
                    <fieldset><legend><?=$this->translate('Customer Status')?>:</legend>
                    <?=$this->form->status?>
                    <label><?=$this->translate('Status')?>*</label>
                    <div class="clr"></div>
                    </fieldset>
                   <br />
                     <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td width="50%"> <?php if(!empty($this->forCutomerWeb)){?>
                    <fieldset>
                    <legend><?php echo ('Select websites for customer')?>:</legend>
                    <div id="pagination">
                    <div style="height:270px; vertical-align:top; overflow:auto">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td class="navigatepage" style="text-align:right;">&lt;&lt;<a  href="javascript:void(0)"> Previous</a> &nbsp;&nbsp;<?php echo "1 of ".ceil(($this->total) / 8)." pages";?>&nbsp;&nbsp;<?php if(($this->total)>8){?><a href="javascript:void(0)" onclick="javascript:callajax(2);"> Next </a>  &gt;&gt;<?php }else{?> <a  href="javascript:void(0)">Next</a> &gt;&gt;<?php }?></td>
                    </tr>
                    </table><table width="100%" cellpadding="0" cellspacing="0">
                    
                    <?php 
					$i=0;
                    foreach($this->forCutomerWeb as $rst) {
						
						
						?>
						<tr class="autoWidth"><td width="33%">
						<input type="checkbox" name="websites[]" value="<?php print $rst['id']; ?>"
                        <? foreach($this->alreadyCustomerWbs as $rsWb)
						{ if($rsWb['webId']===$rst['id']) {?> checked="checked" <? } }?> />
						<?php print $rst['url']; $i++; ?>
						</td></tr>
						<?php 
						
                    }
                    ?>
                                       
                    </table>
                    </div>
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                    <td class="navigatepage" style="text-align:right;">&lt;&lt;<a href="#"> Previous</a> &nbsp;&nbsp;<?php echo "1 of ".ceil(($this->total) / 10)." pages";?>&nbsp;&nbsp;<?php if(($this->total)>10){?><a href="#" onclick="javascript:callajax(2);"> Next </a>  &gt;&gt;<?php }else{?> <a  href="#">Next</a> &gt;&gt;<?php }?></td>
                    </tr>
                    </table> 
                    <? // echo count($this->forCutomerWeb); echo '<br>'; echo count($this->alreadyCustomerWbs);?>
                    </div>
                    </fieldset>
                    <?php }?></td>
                    
                    </tr>
                    </table>
                    <input type="hidden" name="lecturearrayval" id="lecturearrayval" value="" />
                    <div class="btns">
                        <input name="" type="submit" value="<?=$this->translate('Edit Customer')?>" />
                        <input name="" type="button" value="<?=$this->translate('Back to Listing')?>" onclick="back_to_listing();" />
                    </div>
                    </td>
  </tr>
  
 
</table>
                   
                    
                </form>
                </div>
                    
            </div>
		</td>
	</tr>
</table>
<script type="text/javascript">
var myData = "name=William Adama&alias=Husker&job=Commander of the Colonial Fleet";
function callajax(id){ 
var myCars=new Array();
var webSel=new Array();
var boxes = document.getElementsByName('websites[]');
var lecturearr=document.getElementById('lecturearrayval');
var j=0;
var k=0;
for (i = 0; i < boxes.length; i++){
	
	if(boxes[i].checked == true){
		myCars[j]=boxes[i].value;
		webSel[k]=boxes[i].value;
		j++;
		k++;
      // concatval.value=concatval.value+","+boxes[i].value;
	 //  alert(boxes[i].value);
	   
    }
	}
	if(myCars.length>0){
	
		if(lecturearr.value==""){
			lecturearr.value=myCars.join(",");
			}else{
				lecturearr.value=lecturearr.value+','+myCars.join(",");
				}
		
		}
		
		//for(k=0;k<webSel.length;k++)
		//{
			if(webSel.length>0){
			
			if(lecturearr.value==""){
				lecturearr.value=webSel.join(",");
			}else{
				lecturearr.value=lecturearr.value+','+webSel.join(",");
			}
			
			}
		//}
		//alert(webSel.join(","));



				
$.ajax({

            type: "POST",

            url: "<?php echo $this -> baseUrl()?>/admin/customer/allwebpaging/id/"+id+"/csid/<?=$this->csid?>",

            data: "websites="+document.getElementById('lecturearrayval').value,
            success: function(responseText) {
				//alert(responseText);
				$("pagination").html(responseText);
				document.getElementById("pagination").innerHTML=responseText;
            },

            error: function() {

                // alert("AJAX call an epic failure");

            }

        });

        return false;
}
</script>