
<script>
	function sortColumn(col)
	{
		document.getElementById('sort_col').value = col;
		document.customer_list_search.submit();
	}

	function setPaging(obj)
	{
		document.getElementById('perPage').value = obj.value;
		document.customer_list.submit();
	}
	

</script>
<?
 $session = new Zend_Session_Namespace('Customer_Search');
?>
<form name="customer_list" id="customer_list" action="<?=$this->baseUrl()?>/admin/customer/" method="post">  
   	<input type="hidden" name="perPage" id="perPage" value="<?=$session->perPage?>" />
</form>

<table id="twoCols">
    <tr>
        <td colspan="2" class="padding0" height="1"></td>
    </tr>
    <tr>
        <td class="blueBg"  width="200" height="50">&nbsp;</td>
        <td class="greenBg">
            <table width="100%">
                <tr>
                    <td><h2><?=$this->translate('Customer Management')?></h2></td>
                  <td align="right"><a href="<?=$this->url(array('module' => 'admin', 'controller' => 'customer', 'action' => 'add'))?>" class="whiteLink"><strong><?=$this->translate('Add Customer')?></strong></a></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="padding0" height="10"></td>
    </tr>
    <tr style="background:#fff;">
        <?=$this->render('common/left-col.phtml',true)?>
        <td valign="top">
            <div id="breadCrumb"><?=$this->placeholder('breadCrumb')?></div>
            
            
            <div id="eventListing">
          
            	<form name="customer_list_search" id="customer_list_search" method="post" action="<?=$this->baseUrl()?>/admin/customer/">
                    <input type='hidden' name='sort_col' value='' id='sort_col'>
                    <input type="hidden" name="perPage" id="perPage" value="<?=$session->perPage?>" />
                <table class="pagination">
                    <tr>
                        <td align="right">
                           <?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>  
                        </td>
                    </tr>
                </table>
				<table class="searchBy">
                    <tr>
                        <td width="52%">&nbsp;</td>
                        <td><?=$this->translate('Search By')?></td>
                        <td><?=$this->searchform->filters?></td>
                        <td><span id="val-input"><?=$this->searchform->filterText?></span></td>
                        <td class="btn"><input name="submitAction" type="submit" value="<?=$this->translate('Search')?>" /></td>
                        <td class="btn"><input name="submitAction" type="submit" value="<?=$this->translate('Reset')?>" /></td>
                    </tr>
                </table>
                
                </form>
                
                <table class="listing">
                    <tr class="headings">
                       <th width="30%"><div style="width:85px;">
					  
                       <a href="#" class="link" onClick="sortColumn('BusinessName')"><?=$this->translate('Business Name')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'BusinessName'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?>
                       </div> </th>
                       <th>
                       		<a href="#" class="link" onClick="sortColumn('FirstName')"><?=$this->translate('First Name')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'FirstName'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?>
                       </th>
                       <th>
                       	<a href="#" class="link" onClick="sortColumn('LastName')"><?=$this->translate('Last Name')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'LastName'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?>
                        </th>
                       <th>
                       	<a href="#" class="link" onClick="sortColumn('Email')"><?=$this->translate('Email')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'Email'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?>
                       </th>
                       <th><?=$this->translate('Websites')?> 
                       
                       </th>
                       <th> 
                       	<a href="#" class="link" onClick="sortColumn('Status')"><?=$this->translate('Status')?></a> <? if(isset($this->sort_col)){ if($this->sort_col == 'Status'){?><img src="<?=$this->baseUrl()?>/application_data/common/images/<?=$this->order_by?>.gif" alt="sort" /><? }}?>
                       </th>
                       
                      
                  </tr>
                    <?
					
					
						
                        if(count($this->result)>0){
                         foreach($this->result as $rst){
		  	?>
                  <tr class="autoWidth">
                            <td>
                               
					<?php 
                                            $busModel = new Application_Model_DbTable_Business();
                                            $dataBusiness=$busModel->findName($rst['BusinessName']);
                                            print $dataBusiness['businessName'];
                                        ////print $rst['BusinessName']; ?>
                                
                            	<div class="edit-del"><a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'customer', 'action' => 'edit','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Edit')?></a> | 
                                <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'customer', 'action' => 'delete','id' => $rst['id'], 'page' => $this -> page))?>','<?=$this->translate('Are you sure to delete this?')?>')" ><?=$this->translate('Delete')?></a>                              
                                </div>
                            </td>

                            <td ><?php print $rst['FirstName']?></td>
                            <td ><?php print $rst['LastName']?></td>
                            <td ><?php print $rst['Email']?></td>
                            <td > <?  $objModel = new Application_Model_DbTable_CustomerWebsites();
									  
							?>
                                <a href="javascript:void(0);" onclick="window.location = '<?=$this -> url(array('module' => 'admin', 'controller' => 'websites', 'action' => 'index','id' => $rst['id'], 'page' => $this -> page))?>';" ><?=$this->translate('Websites').' ('.$objModel->getCount($where="customerFid=".$rst['id']).')'?></a>
                                
                                </td>
                            <td width="18%"><?php //print ($rst['Status']?$this -> translate('Active'):$this -> translate('Inactive')); ?>
                            <a href="javascript:void(0);" onclick="return deleteRow('<?=$this -> url(array('module' => 'admin', 'controller' => 'customer', 'action' => 'status','id' => $rst['id'], 'page' => $this -> page))?>','<?php echo ('Are you sure to change status?')?>')" ><?php if(!empty($rst['Status']) && $rst['Status']==1) echo 'Active'; else echo 'Inactive'; ?></a>
                            </td> 
                           </tr>

                     <? } 
                       } else {?>
                        <tr>
                        	<td align="center" colspan="3"><?=$this->translate('No record added yet');?></td>
                        </tr>
                   <? }?>
                </table>
                
                <table class="pagination">
                    <tr>
                    	<td width="10%"><?=$this->translate('Results per page')?>:</td>
                        <td><?=$this->searchform->perPage?></td>
                        <td align="right">
                        	<?=$this->paginationControl($this->result,'Sliding','editpaginator.phtml')?>
                        </td>
                    </tr>
                </table>
            </div>
            
            
        </td>
    </tr>
</table>


